### ISSUE TITLE
`make` fails in ./tool/compile_prelude.rb

### ISSUE THREAD

**Issue by judofyr** [imasahiro/rujit#1]
OS 10.9.3

```
0058 pc=0x7fa86374ede0 49 branchif
0034 pc=0x7fa86374ed20 39 trace
0036 pc=0x7fa86374ed30 81 getlocal_OP__WC__0
0038 pc=0x7fa86374ed40 45 invokeblock
0000 pc=0x7fa8637724c0 39 trace
0002 pc=0x7fa8637724d0 39 trace
0004 pc=0x7fa8637724e0 13 putnil
0005 pc=0x7fa8637724e8 51 getinlinecache
0012 pc=0x7fa863772520 81 getlocal_OP__WC__0
0014 pc=0x7fa863772530 22 newarray
0016 pc=0x7fa863772540 18 putstring
---------------
BB0 (pc=0x0)
  0000 StackPop
  0001 GuardTypeNil Exit:0x7fa86374edf0 R:0000
  0013 LoadConstObject Val:0x7fa864035188
  0016 LoadConstString Val:0x7fa86409d968
  0002 Jump TargetBB:bb:1
---------------
BB1 (pc=0x7fa86374ed20)
  0003 Trace flag:1
  0004 EnvLoad Level:0 Index:2
  0005 LoadSelf
  0006 LoadBlock iseq:0x7fa8637717c0
  0007 GuardBlockEqual Exit:0x7fa86374ed40 R:0006 Block:0x7fa86346ae20
  0008 FramePush PC:0x7fa86374ed40 ci:0x7fa86374f030 invokeblock:1 block:0006 argc:2 argv: 0005 0004
  0009 Jump TargetBB:bb:2
---------------
BB2 (pc=0x7fa86374ed40)
  0010 Trace flag:256
  0011 Trace flag:1
  0012 LoadConstNil
  0014 EnvLoad Level:0 Index:2
  0015 AllocArray argc:1 argv: 0014
  0017 AllocString OrigStr:0016
  0018 Exit Exit:0x7fa863772550
---------------
side exit(size=-001): pc=0x7fa86374edf0:
side exit(size=0006): pc=0x7fa863772550:   [-1] = 0005;  [0] = 0004;  [1] = 0008;  [2] = 0012;  [3] = 0013;  [4] = 0015;  [5] = 0017;
side exit(size=0000): pc=0x7fa86374ed40:   [-1] = 0004;
---------------
c-code generation : 0 msec
compiling c code : clang -pipe -fPIC -O3 -g0 -x c -I/Users/magnus/Programming/sources/rujit -I/Users/magnus/Programming/sources/rujit -I/Users/magnus/Programming/sources/rujit/.ext/include/x86_64-darwin13/ -I/Users/magnus/Programming/sources/rujit/include/ -I/Users/magnus/Programming/sources/rujit -include-pch /Users/magnus/Programming/sources/rujit/ruby_jit.h.pch -dynamiclib -Wall -o /tmp/ruby_jit.32365.0.dylib /tmp/ruby_jit.32365.0.c
generated c-code is /tmp/ruby_jit.32365.0.dylib
nativecode generation : 424 msec
./tool/compile_prelude.rb:19:in `pack': no implicit conversion of String into Integer (TypeError)
    from ./tool/compile_prelude.rb:19:in `block in <class:Prelude>'
    from <internal:jit_prelude>:17:in `upto'
    from ./tool/compile_prelude.rb:19:in `<class:Prelude>'
    from ./tool/compile_prelude.rb:9:in `<main>'
trace_invoke_enter  1
trace_invoke  1
trace_child1  0
trace_child2  0
trace_exit  0
trace_side_exit  0
trace_success  1
bloomfilter_entry  1
bloomfilter_hit  31
bloomfilter_total  1081
make: *** [prelude.c] Error 1
```

If I change line 19 to this:

``` ruby
  0x00.upto(0x1f) {|ch| p ch; C_ESC[[ch].pack("C")] ||= "\\%03o" % ch }
```

I get the following output:

```
0
1
2
3
0058 pc=0x7fc2284ab8f0 49 branchif
0034 pc=0x7fc2284ab830 39 trace
0036 pc=0x7fc2284ab840 81 getlocal_OP__WC__0
0038 pc=0x7fc2284ab850 45 invokeblock
0000 pc=0x7fc2284cf2d0 39 trace
0002 pc=0x7fc2284cf2e0 39 trace
0004 pc=0x7fc2284cf2f0 14 putself
0005 pc=0x7fc2284cf2f8 81 getlocal_OP__WC__0
---------------
BB0 (pc=0x0)
  0000 StackPop
  0001 GuardTypeNil Exit:0x7fc2284ab900 R:0000
  0002 Jump TargetBB:bb:1
---------------
BB1 (pc=0x7fc2284ab830)
  0003 Trace flag:1
  0004 EnvLoad Level:0 Index:2
  0005 LoadSelf
  0006 LoadBlock iseq:0x7fc2284ce5d0
  0007 GuardBlockEqual Exit:0x7fc2284ab850 R:0006 Block:0x7fc22852f000
  0008 FramePush PC:0x7fc2284ab850 ci:0x7fc2284abb40 invokeblock:1 block:0006 argc:2 argv: 0005 0004
  0009 Jump TargetBB:bb:2
---------------
BB2 (pc=0x7fc2284ab850)
  0010 Trace flag:256
  0011 Trace flag:1
  0012 LoadSelf
  0013 EnvLoad Level:0 Index:2
  0014 Exit Exit:0x7fc2284cf308
---------------
side exit(size=-001): pc=0x7fc2284ab900:
side exit(size=0000): pc=0x7fc2284ab850:   [-1] = 0004;
side exit(size=0004): pc=0x7fc2284cf308:   [-1] = 0005;  [0] = 0004;  [1] = 0008;  [2] = 0012;  [3] = 0013;
---------------
c-code generation : 0 msec
compiling c code : clang -pipe -fPIC -O3 -g0 -x c -I/Users/magnus/Programming/sources/rujit -I/Users/magnus/Programming/sources/rujit -I/Users/magnus/Programming/sources/rujit/.ext/include/x86_64-darwin13/ -I/Users/magnus/Programming/sources/rujit/include/ -I/Users/magnus/Programming/sources/rujit -include-pch /Users/magnus/Programming/sources/rujit/ruby_jit.h.pch -dynamiclib -Wall -o /tmp/ruby_jit.32573.0.dylib /tmp/ruby_jit.32573.0.c
generated c-code is /tmp/ruby_jit.32573.0.dylib
nativecode generation : 105 msec
4
5
"\\005"
./tool/compile_prelude.rb:19:in `pack': no implicit conversion of String into Integer (TypeError)
    from ./tool/compile_prelude.rb:19:in `block in <class:Prelude>'
    from <internal:jit_prelude>:17:in `upto'
    from ./tool/compile_prelude.rb:19:in `<class:Prelude>'
    from ./tool/compile_prelude.rb:9:in `<main>'
trace_invoke_enter  1
trace_invoke  1
trace_child1  0
trace_child2  0
trace_exit  0
trace_side_exit  0
trace_success  1
bloomfilter_entry  1
bloomfilter_hit  56
bloomfilter_total  1119
```

**Comment by SpringMT** [comment]
I have same issue.

**Comment by imasahiro** [comment]
Thank you for your reports. I'll try to fix it.

**Comment by imasahiro** [comment]
This issue was already solved.
But we still cannot run `make` without error.  ( #2 ) :cry: 
So I would like to close this issue and move on to next.
