### ISSUE TITLE
`make` fails in generating callback.c

### ISSUE THREAD

**Issue by imasahiro** [imasahiro/rujit#2]
Related to #1 
OS is OSX 10.9.5 and C compiler is 

```
$ clang -v
clang version 3.6.0
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

```
generating callback.c
start recording
0107 pc=0x7f7f8b002758 49 branchif
0109 pc=0x7f7f8b002768 13 putnil
0110 pc=0x7f7f8b002770 29 pop
0111 pc=0x7f7f8b002778 39 trace
0113 pc=0x7f7f8b002788 14 putself
[file:<internal:jit_prelude> line:41] exit trace : can not include native method
current trace size=7 is too short to compile.
stop recording
start recording
0107 pc=0x7f7f8b002758 49 branchif
0109 pc=0x7f7f8b002768 13 putnil
0110 pc=0x7f7f8b002770 29 pop
0111 pc=0x7f7f8b002778 39 trace
0113 pc=0x7f7f8b002788 14 putself
[file:<internal:jit_prelude> line:41] exit trace : can not include native method
current trace size=7 is too short to compile.
stop recording
start recording
0107 pc=0x7f7f8b002758 49 branchif
0084 pc=0x7f7f8b0026a0 39 trace
0086 pc=0x7f7f8b0026b0 81 getlocal_OP__WC__0
0088 pc=0x7f7f8b0026c0 45 invokeblock
0000 pc=0x7f7f8a5adca0 81 getlocal_OP__WC__0
0002 pc=0x7f7f8a5adcb0 02 setlocal
0005 pc=0x7f7f8a5adcc8 39 trace
0007 pc=0x7f7f8a5adcd8 39 trace
0009 pc=0x7f7f8a5adce8 01 getlocal
0012 pc=0x7f7f8a5add00 14 putself
0013 pc=0x7f7f8a5add08 01 getlocal
0016 pc=0x7f7f8a5add20 01 getlocal
0019 pc=0x7f7f8a5add38 01 getlocal
0022 pc=0x7f7f8a5add50 01 getlocal
0025 pc=0x7f7f8a5add68 01 getlocal
0028 pc=0x7f7f8a5add80 43 opt_send_simple
0000 pc=0x7f7f8b00e200 39 trace
0002 pc=0x7f7f8b00e210 39 trace
0004 pc=0x7f7f8b00e220 51 getinlinecache
0011 pc=0x7f7f8b00e258 81 getlocal_OP__WC__0
0013 pc=0x7f7f8b00e268 67 opt_aref
0015 pc=0x7f7f8b00e278 83 setlocal_OP__WC__0
0017 pc=0x7f7f8b00e288 39 trace
0019 pc=0x7f7f8b00e298 81 getlocal_OP__WC__0
0021 pc=0x7f7f8b00e2a8 15 putobject
0023 pc=0x7f7f8b00e2b8 67 opt_aref
0025 pc=0x7f7f8b00e2c8 83 setlocal_OP__WC__0
0027 pc=0x7f7f8b00e2d8 39 trace
0029 pc=0x7f7f8b00e2e8 81 getlocal_OP__WC__0
0031 pc=0x7f7f8b00e2f8 51 getinlinecache
0038 pc=0x7f7f8b00e330 60 opt_eq
0040 pc=0x7f7f8b00e340 50 branchunless
0046 pc=0x7f7f8b00e370 18 putstring
0048 pc=0x7f7f8b00e380 20 tostring
0049 pc=0x7f7f8b00e388 15 putobject
0051 pc=0x7f7f8b00e398 81 getlocal_OP__WC__0
0053 pc=0x7f7f8b00e3a8 15 putobject
0055 pc=0x7f7f8b00e3b8 67 opt_aref
0057 pc=0x7f7f8b00e3c8 20 tostring
0058 pc=0x7f7f8b00e3d0 15 putobject
0060 pc=0x7f7f8b00e3e0 81 getlocal_OP__WC__0
[file:../../../../ext/dl/callback/mkcallback.rb line:129] exit trace : can not include native method
---------------
BB0 (pc=0x0)
  0000 StackPop
  0001 GuardTypeNil Exit:0x7f7f8b002768 R:0000
  0026 LoadConstObject Val:0x7f7f8a87bf48
  0034 LoadConstObject Val:0x5ff10c
  0042 LoadConstString Val:0x7f7f8a880570
  0047 LoadConstString Val:0x7f7f8a893418
  0050 LoadConstString Val:0x7f7f8a892888
  0052 LoadConstObject Val:0x5fe10c
  0058 LoadConstString Val:0x7f7f8a892860
  0002 Jump TargetBB:bb:1
---------------
BB1 (pc=0x7f7f8b0026a0)
  0004 EnvLoad Level:0 Index:3
  0005 LoadSelf
  0006 LoadBlock iseq:0x7f7f8a5ad4a0
  0007 GuardBlockEqual Exit:0x7f7f8b0026c0 R:0006 Block:0x7f7f8a5b2220
  0008 FramePush PC:0x7f7f8b0026c0 ci:0x7f7f8b002ca0 invokeblock:1 block:0006 argc:2 argv: 0005 0004
  0009 Jump TargetBB:bb:2
---------------
BB2 (pc=0x7f7f8b0026c0)
  0010 EnvLoad Level:0 Index:2
  0011 EnvStore Level:2 Index:2 Val:0010
  0014 EnvLoad Level:3 Index:2
  0015 LoadSelf
  0016 EnvLoad Level:5 Index:5
  0017 EnvLoad Level:2 Index:5
  0018 EnvLoad Level:2 Index:4
  0019 EnvLoad Level:2 Index:3
  0020 EnvLoad Level:2 Index:2
  0021 GuardMethodCache Exit:0x7f7f8a5add80 R:0015 ci:0x7f7f8a5b2f40
  0022 Jump TargetBB:bb:3
---------------
BB3 (pc=0x7f7f8a5add80)
  0023 FramePush PC:0x7f7f8a5add80 ci:0x7f7f8a5b2f40 invokeblock:0 block:-001 argc:6 argv: 0015 0016 0017 0018 0019 0020
  0027 EnvLoad Level:0 Index:9
  0028 GuardMethodRedefine Exit:0x7f7f8b00e268 klass_flag:16 bop:10
  0029 GuardTypeHash Exit:0x7f7f8b00e268 R:0026
  0030 HashGet Recv:0026 Index:0027
  0031 EnvStore Level:0 Index:4 Val:0030
  0033 EnvLoad Level:0 Index:4
  0035 GuardMethodRedefine Exit:0x7f7f8b00e2b8 klass_flag:16 bop:10
  0036 GuardTypeSpecialConst Exit:0x7f7f8b00e2b8 R:0033
  0037 GuardTypeHash Exit:0x7f7f8b00e2b8 R:0033
  0038 HashGet Recv:0033 Index:0034
  0039 EnvStore Level:0 Index:3 Val:0038
  0041 EnvLoad Level:0 Index:8
  0043 GuardMethodCache Exit:0x7f7f8b00e330 R:0041 ci:0x7f7f8a5b3ae0
  0044 InvokeMethod ci:0x7f7f8a5b3ae0 argc:2 argv: 0041 0042
  0045 GuardTypeNonNil Exit:0x7f7f8b00e350 R:0044
  0046 Jump TargetBB:bb:4
---------------
BB4 (pc=0x7f7f8b00e370)
  0048 AllocString OrigStr:0047
  0049 ObjectToString Val:0048
  0051 EnvLoad Level:0 Index:4
  0053 GuardMethodRedefine Exit:0x7f7f8b00e3b8 klass_flag:16 bop:10
  0054 GuardTypeSpecialConst Exit:0x7f7f8b00e3b8 R:0051
  0055 GuardTypeHash Exit:0x7f7f8b00e3b8 R:0051
  0056 HashGet Recv:0051 Index:0052
  0057 ObjectToString Val:0056
  0059 EnvLoad Level:0 Index:8
  0060 Exit Exit:0x7f7f8b00e3f0
---------------
side exit(size=0011): pc=0x7f7f8b00e330:   [-1] = 0004;  [0] = 0008;  [1] = 0014;  [2] = 0015;  [3] = 0016;  [4] = 0017;  [5] = 0018;  [6] = 0019;  [7] = 0020;  [8] = 0023;  [9] = 0041;  [10] = 0042;
side exit(size=0011): pc=0x7f7f8b00e2b8:   [-1] = 0004;  [0] = 0008;  [1] = 0014;  [2] = 0015;  [3] = 0016;  [4] = 0017;  [5] = 0018;  [6] = 0019;  [7] = 0020;  [8] = 0023;  [9] = 0033;  [10] = 0034;
side exit(size=0000): pc=0x7f7f8b0026c0:   [-1] = 0004;
side exit(size=0008): pc=0x7f7f8a5add80:   [-1] = 0004;  [0] = 0008;  [1] = 0014;  [2] = 0015;  [3] = 0016;  [4] = 0017;  [5] = 0018;  [6] = 0019;  [7] = 0020;
side exit(size=0009): pc=0x7f7f8b00e350:   [-1] = 0004;  [0] = 0008;  [1] = 0014;  [2] = 0015;  [3] = 0016;  [4] = 0017;  [5] = 0018;  [6] = 0019;  [7] = 0020;  [8] = 0023;
side exit(size=-001): pc=0x7f7f8b002768: 
side exit(size=0011): pc=0x7f7f8b00e268:   [-1] = 0004;  [0] = 0008;  [1] = 0014;  [2] = 0015;  [3] = 0016;  [4] = 0017;  [5] = 0018;  [6] = 0019;  [7] = 0020;  [8] = 0023;  [9] = 0026;  [10] = 0027;
side exit(size=0014): pc=0x7f7f8b00e3f0:   [-1] = 0004;  [0] = 0008;  [1] = 0014;  [2] = 0015;  [3] = 0016;  [4] = 0017;  [5] = 0018;  [6] = 0019;  [7] = 0020;  [8] = 0023;  [9] = 0049;  [10] = 0050;  [11] = 0057;  [12] = 0058;  [13] = 0059;
side exit(size=0013): pc=0x7f7f8b00e3b8:   [-1] = 0004;  [0] = 0008;  [1] = 0014;  [2] = 0015;  [3] = 0016;  [4] = 0017;  [5] = 0018;  [6] = 0019;  [7] = 0020;  [8] = 0023;  [9] = 0049;  [10] = 0050;  [11] = 0051;  [12] = 0052;
---------------
c-code generation : 1 msec
compiling c code : clang -pipe -fPIC -O0 -g3 -x c -I/Users/masa/src/ruby/tmp -I/Users/masa/src/ruby -I/Users/masa/src/ruby/tmp/.ext/include/x86_64-darwin13/ -I/Users/masa/src/ruby/include/ -I/Users/masa/src/ruby -include-pch /Users/masa/src/ruby/tmp/ruby_jit.h.pch -dynamiclib -Wall -o /tmp/ruby_jit.34075.0.dylib /tmp/ruby_jit.34075.0.c
generated c-code is /tmp/ruby_jit.34075.0.dylib
nativecode generation : 100 msec
stop recording
invoke compiled trace at file:<internal:jit_prelude> line:36 trace=0x7f7f8a5b1ff0
exit6 : pc=0x007f7f8b002768
[file:<internal:jit_prelude> line:36] trace for 0x7f7f8b002758 is exit from 0x7f7f8b002768
invoke compiled trace at file:<internal:jit_prelude> line:36 trace=0x7f7f8a5b1ff0
exit6 : pc=0x007f7f8b002768
[file:<internal:jit_prelude> line:36] trace for 0x7f7f8b002758 is exit from 0x7f7f8b002768
invoke compiled trace at file:<internal:jit_prelude> line:36 trace=0x7f7f8a5b1ff0
exit6 : pc=0x007f7f8b002768
[file:<internal:jit_prelude> line:36] trace for 0x7f7f8b002758 is exit from 0x7f7f8b002768
invoke compiled trace at file:<internal:jit_prelude> line:36 trace=0x7f7f8a5b1ff0
exit3 : pc=0x007f7f8b0026c0
[file:<internal:jit_prelude> line:36] trace for 0x7f7f8b002758 is exit from 0x7f7f8b0026c0
start recording
0088 pc=0x7f7f8b0026c0 45 invokeblock
0000 pc=0x7f7f8a5ad860 81 getlocal_OP__WC__0
0002 pc=0x7f7f8a5ad870 84 setlocal_OP__WC__1
0004 pc=0x7f7f8a5ad880 39 trace
0006 pc=0x7f7f8a5ad890 39 trace
0008 pc=0x7f7f8a5ad8a0 85 putobject_OP_INT2FIX_O_0_C_
0009 pc=0x7f7f8a5ad8a8 51 getinlinecache
0016 pc=0x7f7f8a5ad8e0 28 newrange
0018 pc=0x7f7f8a5ad8f0 41 send
0000 pc=0x7f7f8b002400 39 trace
0002 pc=0x7f7f8b002410 39 trace
0004 pc=0x7f7f8b002420 14 putself
0005 pc=0x7f7f8b002428 43 opt_send_simple
0007 pc=0x7f7f8b002438 49 branchif
0019 pc=0x7f7f8b002498 39 trace
0021 pc=0x7f7f8b0024a8 14 putself
[file:<internal:jit_prelude> line:28] exit trace : can not include native method
---------------
BB0 (pc=0x0)
  0000 LoadSelf
  0001 LoadBlock iseq:0x7f7f8a5a7ba0
  0002 StackPop
  0003 GuardBlockEqual Exit:0x7f7f8b0026c0 R:0001 Block:0x7f7f8a5b2180
  0004 FramePush PC:0x7f7f8b0026c0 ci:0x7f7f8b002ca0 invokeblock:1 block:0001 argc:2 argv: 0000 0002
  0010 LoadConstFixnum Val:0x1
  0011 LoadConstFixnum Val:0xb
  0005 Jump TargetBB:bb:1
---------------
BB1 (pc=0x7f7f8b0026c0)
  0006 EnvLoad Level:0 Index:2
  0007 EnvStore Level:1 Index:3 Val:0006
  0012 AllocRange Low:0010 High:0011 Flag:1
  0013 LoadSelfAsBlock iseq:0x7f7f8a5ad4a0
  0014 GuardMethodCache Exit:0x7f7f8a5ad8f0 R:0012 ci:0x7f7f8a42c650
  0015 GuardBlockEqual Exit:0x7f7f8a5ad8f0 R:0013 Block:0x1016e2c60
  0016 Jump TargetBB:bb:2
---------------
BB2 (pc=0x7f7f8a5ad8f0)
  0017 FramePush PC:0x7f7f8a5ad8f0 ci:0x7f7f8a42c650 invokeblock:0 block:0013 argc:1 argv: 0012
  0020 LoadSelf
  0021 LoadSelf
  0022 GuardMethodCache Exit:0x7f7f8b002428 R:0021 ci:0x7f7f8a42c870
  0023 InvokeNative fptr:0x1013a4050 argc:0 argv:
  0024 GuardTypeNil Exit:0x7f7f8b002448 R:0023
  0025 Jump TargetBB:bb:3
---------------
BB3 (pc=0x7f7f8b002498)
  0027 LoadSelf
  0028 Exit Exit:0x7f7f8b0024b0
---------------
side exit(size=0000): pc=0x7f7f8b0026c0: 
side exit(size=0002): pc=0x7f7f8a5ad8f0:   [-1] = 0002;  [0] = 0004;  [1] = 0012;
side exit(size=0004): pc=0x7f7f8b0024b0:   [-1] = 0002;  [0] = 0004;  [1] = 0012;  [2] = 0017;  [3] = 0027;
side exit(size=0004): pc=0x7f7f8b002428:   [-1] = 0002;  [0] = 0004;  [1] = 0012;  [2] = 0017;  [3] = 0020;
side exit(size=0003): pc=0x7f7f8b002448:   [-1] = 0002;  [0] = 0004;  [1] = 0012;  [2] = 0017;
---------------
c-code generation : 0 msec
compiling c code : clang -pipe -fPIC -O0 -g3 -x c -I/Users/masa/src/ruby/tmp -I/Users/masa/src/ruby -I/Users/masa/src/ruby/tmp/.ext/include/x86_64-darwin13/ -I/Users/masa/src/ruby/include/ -I/Users/masa/src/ruby -include-pch /Users/masa/src/ruby/tmp/ruby_jit.h.pch -dynamiclib -Wall -o /tmp/ruby_jit.34075.1.dylib /tmp/ruby_jit.34075.1.c
generated c-code is /tmp/ruby_jit.34075.1.dylib
nativecode generation : 88 msec
link trace. parent=0x1016f10f0, child=0x7f7f8a42c1c0
stop recording
invoke compiled trace at file:<internal:jit_prelude> line:36 trace=0x7f7f8a5b1ff0
exit8 : pc=0x007f7f8b00e3f0
[file:<internal:jit_prelude> line:36] trace for 0x7f7f8b002758 is exit from 0x7f7f8b00e3f0
invoke compiled trace at file:<internal:jit_prelude> line:36 trace=0x7f7f8a5b1ff0
exit3 : pc=0x007f7f8b0026c0
[file:<internal:jit_prelude> line:36] trace for 0x7f7f8b002758 is exit from 0x7f7f8b0026c0
invoke compiled trace at file:<internal:jit_prelude> line:36 trace=0x7f7f8a42c1c0
exit1 : pc=0x7f7f8b0026c0
[file:<internal:jit_prelude> line:36] trace for 0x7f7f8b002758 is exit from 0x7f7f8b0026c0
start recording
current trace size=1 is too short to compile.
stop recording
invoke compiled trace at file:<internal:jit_prelude> line:36 trace=0x7f7f8a5b1ff0
exit6 : pc=0x007f7f8b002768
[file:<internal:jit_prelude> line:36] trace for 0x7f7f8b002758 is exit from 0x7f7f8b002768
<internal:jit_prelude>:44: [BUG] Stack consistency error (sp: 91, bp: 92)
ruby 2.2.0dev (2014-09-20 trunk 47651) [x86_64-darwin13]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0017 p:0143 s:0091 e:000091 METHOD <internal:jit_prelude>:44 [FINISH]
c:0016 p:---- s:0086 E:000af8 CFUNC  :collect
c:0015 p:0090 s:0083 E:000a60 METHOD ../../../../ext/dl/callback/mkcallback.rb:129
c:0014 p:0030 s:0064 e:000062 BLOCK  ../../../../ext/dl/callback/mkcallback.rb:199
c:0013 p:0090 s:0060 e:000059 METHOD <internal:jit_prelude>:37
c:0012 p:0020 s:0054 E:001898 BLOCK  ../../../../ext/dl/callback/mkcallback.rb:198
c:0011 p:0090 s:0051 e:000050 METHOD <internal:jit_prelude>:37
c:0010 p:0016 s:0045 E:0008f0 BLOCK  ../../../../ext/dl/callback/mkcallback.rb:197
c:0009 p:0074 s:0039 e:000038 BLOCK  ../../../../ext/dl/callback/mkcallback.rb:119 [FINISH]
c:0008 p:---- s:0036 e:000035 CFUNC  :each
c:0007 p:0013 s:0033 e:000032 METHOD ../../../../ext/dl/callback/mkcallback.rb:110
c:0006 p:0007 s:0028 E:000878 BLOCK  ../../../../ext/dl/callback/mkcallback.rb:196
c:0005 p:0041 s:0025 e:000024 METHOD ../../../../ext/dl/callback/mkcallback.rb:177
c:0004 p:0013 s:0018 E:000818 BLOCK  ../../../../ext/dl/callback/mkcallback.rb:195
c:0003 p:0090 s:0015 e:000014 METHOD <internal:jit_prelude>:37
c:0002 p:0414 s:0009 E:000028 EVAL   ../../../../ext/dl/callback/mkcallback.rb:194 [FINISH]
c:0001 p:0000 s:0002 E:001f10 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
../../../../ext/dl/callback/mkcallback.rb:194:in `<main>'
<internal:jit_prelude>:37:in `each'
../../../../ext/dl/callback/mkcallback.rb:195:in `block in <main>'
../../../../ext/dl/callback/mkcallback.rb:177:in `gen_callback_file'
../../../../ext/dl/callback/mkcallback.rb:196:in `block (2 levels) in <main>'
../../../../ext/dl/callback/mkcallback.rb:110:in `foreach_proc_entry'
../../../../ext/dl/callback/mkcallback.rb:110:in `each'
../../../../ext/dl/callback/mkcallback.rb:119:in `block in foreach_proc_entry'
../../../../ext/dl/callback/mkcallback.rb:197:in `block (3 levels) in <main>'
<internal:jit_prelude>:37:in `each'
../../../../ext/dl/callback/mkcallback.rb:198:in `block (4 levels) in <main>'
<internal:jit_prelude>:37:in `each'
../../../../ext/dl/callback/mkcallback.rb:199:in `block (5 levels) in <main>'
../../../../ext/dl/callback/mkcallback.rb:129:in `gencallback'
../../../../ext/dl/callback/mkcallback.rb:129:in `collect'
<internal:jit_prelude>:44:in `each'

-- C level backtrace information -------------------------------------------
0   miniruby                            0x00000001013b1d35 rb_vm_bugreport + 149
1   miniruby                            0x00000001012609b4 rb_bug + 468
2   miniruby                            0x0000000101399ef8 vm_exec_core + 17144
3   miniruby                            0x00000001013a60d0 vm_exec + 128
4   miniruby                            0x000000010139549c vm_call0 + 1532
5   miniruby                            0x00000001013ae1fe rb_call0 + 334
6   miniruby                            0x00000001013a2ff9 rb_iterate + 457
7   miniruby                            0x00000001013a30cd rb_block_call + 45
8   miniruby                            0x0000000101257876 enum_collect + 54
9   miniruby                            0x00000001013b03d1 vm_call_cfunc + 1041
10  miniruby                            0x00000001013993ac vm_exec_core + 14252
11  miniruby                            0x00000001013a60d0 vm_exec + 128
12  miniruby                            0x00000001013ab394 invoke_block_from_c + 2484
13  miniruby                            0x00000001013a2a40 rb_yield + 192
14  miniruby                            0x0000000101223099 rb_ary_each + 89
15  miniruby                            0x00000001013b03d1 vm_call_cfunc + 1041
16  miniruby                            0x00000001013afcbd vm_call_method + 1037
17  miniruby                            0x00000001013993ac vm_exec_core + 14252
18  miniruby                            0x00000001013a60d0 vm_exec + 128
19  miniruby                            0x00000001013a71b9 rb_iseq_eval_main + 393
20  miniruby                            0x0000000101269784 ruby_exec_internal + 148
21  miniruby                            0x00000001012696ae ruby_run_node + 78
22  miniruby                            0x00000001012206ff main + 79

-- Other runtime information -----------------------------------------------

* Loaded script: ../../../../ext/dl/callback/mkcallback.rb

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

make[2]: *** [callback.c] Abort trap: 6
make[2]: *** Deleting file `callback.c'
make[1]: *** [ext/dl/callback/all] Error 2
make: *** [build-ext] Error 2
```

**Comment by imasahiro** [comment]
I will close this issue because the commit 6aa99a9aff78f fixes build failure.
